Deprecated `BundleExtension` and `ConfigurableBundleExtension`
Becklyn/BecklynRadBundle pull request #109
Opened 2020-07-01 16:23 UTC by keichinger

| Q             | A
| ------------- | --------------------------------------------------------------------- |
| BC breaks?    |no                                                                |
| New feature?  |no                    |
| Improvement?  | no     |
| Bug fix?      |no                                                                |
| Deprecations? | yes    |
| Docs PR       | **missing**                                   |

2020-07-01 16:37 UTC, keichinger commented
Did I fail at creating the BC compat layer or is this just a PhpStan issue that needs to be silenced, @apfelbox?

2020-07-02 07:47 UTC, apfelbox requested changes

2020-07-02 07:47 UTC, apfelbox commented on src/Bundle/BundleExtension.php
> +    class BundleExtension extends NewBundleExtension
Both should be deprecated, as we still want to remove this calls and can't remove it, if they still use the name from RAD.

2020-07-02 07:48 UTC, apfelbox commented
PhpStan always had issues with conditionally loaded classes. The BC layer looks okay

2020-07-03 07:54 UTC, apfelbox commented on src/Bundle/BundleExtension.php
> +if (\class_exists(NewBundleExtension::class))
You can remove the `class_exists()`, because the class will always exist? We load it via Composer.

2020-07-03 07:54 UTC, apfelbox commented on composer.json
>          "php": ">=7.3",
We should probably change this back to `^7.3`

2020-07-03 08:00 UTC, apfelbox approved these changes

2020-07-03 08:00 UTC, merged